version = 1

[*]
c = 32768
n-gpu-layers = all
load-on-startup = false

[default]
model = ./models/Qwen3.6-27B-Q5_K_M.gguf
alias = qwen3.6-27b-q5_k_m

;[qwen3.6-27b-q4]
;model = ./models/Qwen3.6-27B-Q4_K_M.gguf

;[qwen3.6-35b-a3b-q4]
;model = ./models/Qwen3.6-35B-A3B-UD-Q4_K_M.gguf

[gemma-4-26b-a4b-it-q4]
model = ./models/gemma-4-26B-A4B-it-Q4_K_M.gguf
